### PR TITLE
Updated "logo.png" 

### PR DESCRIPTION
**Pull request by rquarry**
New logo was copied out of the pdf docs. I was able to build the branch and test run it; looks much better than the old splash graphic.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
Thanks. Can you pushed the code also?

**Comment by rquarry** [comment]
Sorry I think I may have been confusing in my commit comment. The only actual file that was changed was "osrmt/build-resources/common/runtime-lib/resources.jar" and I believe that's being pushed as it's listed under the "changed files" tab.

I'm still a n00b at this, so let me know if I'm missing something.

**Comment by ZoranPandovski** [comment]
Thats ok @rquarry . In you commit you just remove build-resources/common/runtime-lib/resources.jar. I think you need to push also the new change. Can you check that?

**Comment by rquarry** [comment]
Thanks @ZoranPandovski. The jar file "build-resources/common/runtime-lib/resources.jar" **IS** the update here. It contains the file "logo.png" that I changed. There is **no** change to the code in the repo, just the (binary) update to the jar file, so that's why you don't see any code being pushed.

If you accept this merge, the .jar file will be updated = the updated "logo.png" in that .jar will load at runtime.

I hope this makes sense.

**Review by ZoranPandovski — APPROVED** [review]

**Comment by ZoranPandovski** [comment]
Can you pull the master and test? If there are some issues feel free to add another commit. Thanks

**Comment by rquarry** [comment]
Sure, I will test and post my results in issue #50. Might take me a couple days.

**Pull request merged**
